apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: nodeapp
    spec:
     containers:
     - name: nodeserver
       image: venugopalmanthena/docker-nodejs-demo:tagVersion
       ports:
         -  containerPort: 3000
  selector:
    matchLabels:
      app: nodeapp
